/**
 * @file    fa.h
 *
 * @brief   non-deterministic finite automaton to be generated by regular expressions
 *          and used for lexical analysis of a document. Transition symbol set includes
 *          all ascii values.
 *
 * @author  Connor Nolan
**/

#ifndef __FA_H__
#define __FA_H__

#include <vector>
#include <list>
#include <istream>
#include <utility>
#include "fa_trans_table.h"
#include "../constants.h"

class FA
{
public:
    FA(const FAtTable& table, const std::vector<int>& endStates);

    std::list<std::pair<std::string, int> > run(std::istream& input);
private:

    std::pair<std::string, int> step(std::istream& input, int state, std::string s);

    int m_numStates;
    int* m_endStates;
    FAtTable m_tTable;
};

#endif
